#
# this file provides configuration for Travis Continuous Integration
#

language: php

dist: trusty

before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]]; then composer require --dev --no-update phpunit/phpunit ~4; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then composer require --dev --no-update phpunit/phpunit ~5; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then composer require --dev --no-update phpunit/phpunit ~6; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:1} != "7" ]]; then composer remove --dev --no-update vimeo/psalm; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.1" ]]; then composer remove --dev --no-update rector/rector; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.2" ]]; then composer remove --dev --no-update rector/rector; fi


install: composer install
 
matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2

script: vendor/bin/phpunit --coverage-text -c phpunit.xml --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
  - if [[ ${TRAVIS_PHP_VERSION:0:1} = "7" ]]; then travis_retry php vendor/bin/psalm; fi

